// <auto-generated />
using System;
using Company.Services.User.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company.Services.User.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Company.Services.Model.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("220e7528-3cd7-493b-9ab3-d7f369bdb3dc"),
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("b8b55a7b-c18a-4ee4-964b-f8f22bf93663"),
                            Name = "Mary"
                        },
                        new
                        {
                            Id = new Guid("8fcf47f5-b08b-4f3c-a78f-38b0ffedc822"),
                            Name = "Karen"
                        },
                        new
                        {
                            Id = new Guid("f3a5e45f-c627-4588-8c76-9ce908c44fd8"),
                            Name = "Steve"
                        },
                        new
                        {
                            Id = new Guid("d131e104-6ddc-4470-8bdf-cf43833e216f"),
                            Name = "Lauren"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
